### ISSUE TITLE
Update latest

### ISSUE THREAD

**Issue by AE1NS** [urbanairship/cordova-gimbal-sdk#5]
Will this plugin be updated to the latest platform structures / latest version?

i.e. I cant run this inside my capacitor project because Android throws an error. I have to refactor
```
repositories {
	mavenCentral()
}

dependencies {
	compile group: 'com.gimbal.android.v3', name: 'gimbal-sdk', version: '3.1.1'
	compile group: 'com.gimbal.android.v3', name: 'gimbal-slf4j-impl', version: '3.1.1'
}
```
to
```
allprojects {
    repositories {
        google()
        jcenter()
    }
}

dependencies {
	implementation 'com.gimbal.android.v4:gimbal-sdk:4.7.0'
	implementation 'com.gimbal.android.v4:gimbal-slf4j-impl:4.7.0'
}
```
to fix it.

**Comment by Ulrico972** [comment]
Thank you, we will take a look.

**Comment by Ulrico972** [comment]
Hello, I just want to inform you that we have pushed some changes to use the versions you needed.

**Comment by AE1NS** [comment]
Thank you. Can you also have a look to the other tickets?
https://github.com/urbanairship/cordova-gimbal-bridge/issues/9
https://github.com/urbanairship/airship-location-cordova/issues/3
Otherwise we cant use the Gimbal integration with airship.
